export const METRIC_CATEGORIES = [
  {
    category: 'ATTACK',
    metrics: [
      'Striker quality',
      'Finishing',
      'Left-wing threat',
      'Right-wing threat',
      'Front-line creativity',
      'One-v-one ability',
      'Counterattacking threat',
      'Penalty-box movement',
      'Aerial attacking threat',
      'Overall attacking balance',
    ],
  },
  {
    category: 'MIDFIELD',
    metrics: [
      'Passing quality',
      'Tempo control',
      'Press resistance',
      'Ball progression',
      'Defensive midfield protection',
      'Midfield pressing',
      'Creativity',
      'Transition play',
      'Ball retention',
      'Overall midfield balance',
    ],
  },
  {
    category: 'DEFENCE',
    metrics: [
      'Best centre-back quality',
      'CB partnership',
      'Full-back defending',
      'Full-back attacking',
      'One-v-one defending',
      'Aerial defending',
      'Recovery defending',
      'Defensive build-up',
      'High-line suitability',
      'Overall defensive unit',
    ],
  },
  {
    category: 'GOALKEEPING',
    metrics: [
      'Shot stopping',
      'Distribution',
      'Sweeping',
      'Cross claiming',
      'Penalty saving',
      'Reflexes',
      'Reliability',
      'Big-match performance',
      'Build-up compatibility',
      'Overall goalkeeper score',
    ],
  },
  {
    category: 'MANAGER & TACTICS',
    metrics: [
      'Manager current quality',
      'Manager-squad compatibility',
      'Build-up structure',
      'Positional play',
      'Pressing system',
      'Counterattacking structure',
      'Defensive organisation',
      'Tactical flexibility',
      'In-game adaptability',
      'Overall tactical ceiling',
    ],
  },
  {
    category: 'TECHNICAL',
    metrics: [
      'First touch',
      'Close control',
      'Short passing',
      'Long passing',
      'Dribbling',
      'Crossing',
      'Chance creation',
      'Progressive passing',
      'Shooting technique',
      'Overall technical quality',
    ],
  },
  {
    category: 'PHYSICAL',
    metrics: [
      'Pace',
      'Acceleration',
      'Strength',
      'Stamina',
      'Aerial athleticism',
      'Duel ability',
      'Recovery speed',
      'Defensive athleticism',
      'Attacking explosiveness',
      'Overall physical profile',
    ],
  },
  {
    category: 'MENTALITY',
    metrics: [
      'Leadership',
      'Composure',
      'Work rate',
      'Tactical intelligence',
      'Pressure handling',
      'Discipline',
      'Resilience',
      'Big-match reliability',
      'Competitive mentality',
      'Overall mental profile',
    ],
  },
  {
    category: 'CHEMISTRY & BALANCE',
    metrics: [
      'GK-CB compatibility',
      'CB partnership compatibility',
      'Full-back balance',
      'Midfield balance',
      'Attack-midfield connection',
      'Left-side balance',
      'Right-side balance',
      'Central spine',
      'Defensive protection',
      'Overall XI balance',
    ],
  },
  {
    category: 'MATCH SITUATIONS',
    metrics: [
      'Breaking low blocks',
      'Defending a lead',
      'Chasing a goal',
      'Countering elite opponents',
      'Playing through high press',
      'High pressing',
      'Set-piece threat',
      'Knockout-match suitability',
      'League consistency',
      'Best complete XI',
    ],
  },
] as const;

export const METRIC_NAMES = METRIC_CATEGORIES.flatMap(({ category, metrics }) =>
  metrics.map((metric, offset) => ({ category, metric, offset })),
);

if (METRIC_NAMES.length !== 100) {
  throw new Error(
    `The evaluation contract requires exactly 100 metrics; found ${METRIC_NAMES.length}`,
  );
}
